### ISSUE TITLE
Q.1 FizzBuzz

### ISSUE THREAD

**Issue by PrajjvalD** [PrajjvalD/Interview-QnA#3]
Write a program that prints the numbers from 1 to 100. But for multiples of three, print “Fizz” instead of the number, and for the multiples of five, print “Buzz”. For numbers that are multiples of both three and five, print “FizzBuzz”.

**Comment by Aksharma2799** [comment]
done

**Comment by PrajjvalD** [comment]
Reopen, waiting for others response

**Comment by Bhushanrock70** [comment]
public class FizzBuzz {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
			for(int i=1;i<=100;i++)
			{
				if(i%3==0 && i%5==0) {
					System.out.println("FizzBuzz");
				}
				else if(i%3==0){
					System.out.println("Fizz");
				}
				else if(i%5==0) {
					System.out.println("Buzz");
				}
				else {
					System.out.println(i);
				}
			}
	}

}
Done
