### ISSUE TITLE
Q.2 Palindrome Number

### ISSUE THREAD

**Issue by Aksharma2799** [PrajjvalD/Interview-QnA#5]
Write a function to determine if a given string is a palindrome. A palindrome is a word, phrase, number, or other sequence of characters that reads the same forward and backward.

Input: x = 121
Output: true

Input: x = 'abcba'
Output: true

**Explanation**: 121 reads as 121 from left to right and from right to left.

**Comment by Bhushanrock70** [comment]
//Write a function to determine if a given string is a palindrome. 
//A palindrome is a word, phrase, number, or other sequence of characters that 
//reads the same forward and backward.

//Input: x = 121
//Output: true



public class Palindrome {

    public static boolean isPalindrome(Object x) {
        String s = x.toString();
      
        int n = s.length();
        for (int i = 0; i < n / 2; i++) {
            if (s.charAt(i) != s.charAt(n - 1 - i)) {
                return false;
            }
        }
        return true;
    }

    public static void main(String[] args) {
        System.out.println(isPalindrome(121));      
        System.out.println(isPalindrome("bsdk")); 
    }
}
